### ISSUE TITLE
Universal Footer and Header

### ISSUE THREAD

**Issue by mrdunster** [mrdunster/Special_Technical_Services#1]
I tried using the w3 include but that didn't work.

http://www.w3schools.com/howto/howto_html_include.asp

Or I am just doing this wrong...

**Comment by ivanempire** [comment]
Right, so you need a server to have that working. Frankly, you can already put your code up on DigitalOcean and then, every time you push to git, the server code will be updated as well :D

**Comment by mrdunster** [comment]
Would you be able to show me how to do this sometime this week?

**Comment by ivanempire** [comment]
So, try to add the universal footer and header through PHP now that it works.
