### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by mrdunster** [mrdunster/Special_Technical_Services#3]
When I go on a mobile device the web page doesn't adapt for some reason and use the medium or small resolution

**Comment by mrdunster** [comment]
![screenshot_2016-05-05-15-42-26](https://cloud.githubusercontent.com/assets/18058261/15055028/6fc8f5e0-12d8-11e6-904f-4ad1260a778b.png)

**Comment by ivanempire** [comment]
OK this is an easy fix - I'll do that in a bit.

**Comment by mrdunster** [comment]
Is this something I am doing wrong with UIkit?
